# SPDX-License-Identifier: GPL-2.0-only
# Auto-load the venator module at boot so we don't have to insmod
# after every reboot. systemd-modules-load.service handles this very
# early in boot (before sysinit.target).
venator
